[{
		"name": "Dr. Alex Hunt",
		"title": "Professor of English, Haley Endowed Professor of Western Studies, and Director of The Center for the Study of The American West",
		"dep": "English, Philosophy, and Modern Languages, Department of ",
		"building": "Classroom Center",
		"room": "319 H",
		"phone": "806-651-2457",
		"email": "ahunt@wtamu.edu",
		"thumb": "/images/alex-hunt-bodyphoto.jpg",
		"url": "/alex-hunt",
		"expertise": "American Literature&#8212;the West, Environmental Literature, Ethnic Literature, and Regionalism Southwest Border Studies"
	},
	{
		"name": "Dr. Amjad Abdullat",
		"title": "Associate Dean of Undergraduate Programs for The College of Business and Professor of Computer Information Systems",
		"dep": "Computer Information and Decision Management, Department of",
		"building": "Classroom Center",
		"room": "220 A",
		"phone": "806-651-2443",
		"email": "aabdullat@wtamu.edu",
		"thumb": "/images/amjad-abdullat-bodyphoto.jpg",
		"url": "/amjad-abdullat",
		"expertise": "Information Technology and Middle Eastern Affairs and Conflict"
	},
	{
		"name": "Dr. Amy Andersen",
		"title": "Associate Provost for Academic Affairs and Associate Professor of Education",
		"dep": "Academic Affairs",
		"building": "Old Main",
		"room": "307 D",
		"phone": " 806-651-2044",
		"email": "aandersen@wtamu.edu",
		"thumb": "/images/amy-andersen-headphoto.jpg",
		"url": "/amy-andersen",
		"expertise": "Early Childhood Education, Early Literacy, Reading/Language Arts Education, Reading/Language Arts Integration, and Reading/Language/Arts Integration"
	},
	{
		"name": "Dr. Andrew Reynolds",
		"title": "Associate Professor of Spanish and Director of The Spanish Program",
		"dep": "English, Philosophy, and Modern Languages, Department of ",
		"building": "Classroom Center",
		"room": "319 H",
		"phone": "806-651-2466",
		"email": "areynolds@wtamu.edu",
		"thumb": "/images/andrew-reynolds-bodyphoto.jpg",
		"url": "/andrew-reynolds",
		"expertise": "Latin American and Spanish Literature of the 19th and 20th Centuries"
	},
	{
		"name": "Dr. Angela Phillips",
		"title": "Assistant Professor of Nursing and FNP Program Director",
		"dep": "Nursing, Department of ",
		"building": "Old Main",
		"room": "310 C",
		"phone": "806-651-2662",
		"email": "aphillips@wtamu.edu",
		"thumb": "/images/angela-phillips-bodyphoto.jpg",
		"url": "/angela-phillips",
		"expertise": "Family Medicine and Nephrology Nursing"
	},
	{
		"name": "Dr. Angela Spaulding",
		"title": "Dean of The Graduate School, Vice President of Research and Compliance, and Professor of Educational Leadership",
		"dep": "Graduate School",
		"building": "Kilgore Research Center",
		"room": "104 A",
		"phone": "806-651-2731",
		"email": "aspaulding@wtamu.edu",
		"thumb": "/images/angela-spaulding-bodyphoto.jpg",
		"url": "/angela-spaulding",
		"expertise": "Conflict Resolution, Cross Cultural Understanding, Educational Leadership and Group Dynamics, Service Learning, and Team Building"
	},
	{
		"name": "Mrs. Ann Wallace",
		"title": "Clinical Instructor",
		"dep": "Communication Disorders, Department of",
		"building": "Virgil Henson Activities Center",
		"room": "242 S",
		"phone": "806-651-5114",
		"email": "awallace@wtamu.edu",
		"thumb": "/images/ann-wallace-bodyphoto.jpg",
		"url": "/ann-wallace",
		"expertise": "Swallowing Disorders and Voice Disorders"
	},
	{
		"name": "Dr. Anne Macy",
		"title": "Gene Edwards Professor of Finance",
		"dep": "Accounting, Economics and Finance",
		"building": "Classroom Center",
		"room": "215 C",
		"phone": "806-651-2523",
		"email": "amacy@wtamu.edu",
		"thumb": "/images/anny-macy-bodyphoto.jpg",
		"url": "/anne-macy",
		"expertise": "General Economics, Investments, and Personal Finance"
	},
	{
		"name": "Mrs. Anne C. Medlock-Ely",
		"title": "Associate Professor of Theatre - Costume Design",
		"dep": "Art, Theatre and Dance",
		"building": "Sybil B. Harrington Fine Arts Complex",
		"room": "120",
		"phone": "806-651-3254",
		"email": "amedlock@wtamu.edu",
		"thumb": "/images/anne-medlock-headphoto.jpg",
		"url": "/anne-medlock",
		"expertise": "Costume Construction, Costume Design, Fabric Modification, and Stage Make-Up"
	},
	{
		"name": "Dr.  Nabarun Ghosh",
		"title": "Associate Professor of Biology",
		"dep": "Life, Earth and Environmental Sciences, Department of ",
		"building": "Agriculture and Natural Sciences Building",
		"room": "340",
		"phone": "806-651-2571",
		"email": "nghosh@wtamu.edu",
		"thumb": "/images/nabarun-ghosh-bodyshot.jpg",
		"url": "/arun-ghosh",
		"expertise": "Aerobiology and Allergy, Air and Water Quality, Bioinformatics, Biotechnology, Crop Breeding, Cytogenetics, Digital, Fluorescence and Electron Microscopy, Light, Tissue Culture, and Toxicology"
	},
	{
		"name": "Dr. Ashley J. Campbell",
		"title": "Helen Piehl Professor of Education",
		"dep": "Education, Department of",
		"building": "Old Main Main",
		"room": "441",
		"phone": "806-651-2906",
		"email": "acampbell@wtamu.edu",
		"thumb": "/images/ashley-campbell-bodyphoto.jpg",
		"url": "/ashley-campbell",
		"expertise": "Gender Equity in Science and Science Education"
	},
	{
		"name": "Dr. B.J. Brooks",
		"title": "Associate Professor of Music",
		"dep": "Music, School of",
		"building": "Sybil B. Harrington Fine Arts Complex",
		"room": "211",
		"phone": "806-651-2862",
		"email": "bbrooks@mail.wtamu.edu",
		"thumb": "/images/benjamin-brooks-bodyphoto.jpg",
		"url": "/benjamin-brooks",
		"expertise": "Electroacoustic Composition, Music Composition, Music Technology, and Music Theory"
	},
	{
		"name": "Dr. B.A. Stewart",
		"title": "Director of The Institute of Dryland Agriculture",
		"dep": "Agricultural Sciences",
		"building": "Agriculture and Natural Sciences Building",
		"room": "210",
		"phone": "806-651-2299",
		"email": "bstewart@wtamu.edu",
		"thumb": "/images/bobby-stewart-bodyphoto.jpg",
		"url": "/bobby-stewart",
		"expertise": "Animal Waste Management, Environmental Quality, and Soil and Water Conservation"
	},
	{
		"name": "Dr. Bonney MacDonald",
		"title": "Professor of English",
		"dep": "English, Philosophy, and Modern Languages, Department of ",
		"building": "Classroom Center",
		"room": "319 E",
		"phone": "806-651-2456",
		"email": "bmacdonald@wtamu.edu",
		"thumb": "/images/bonney-macdonald-bodyphoto.jpg",
		"url": "/bonney-macdonald",
		"expertise": "American Literature, Film and Culture, and Western American Literature"
	},
	{
		"name": "Dr. Bonnie B. Pendleton",
		"title": "Associate Professor of Integrated Pest Management - Entomology",
		"dep": "Agricultural Sciences",
		"building": "Agriculture and Natural Sciences Building",
		"room": "204",
		"phone": "806-651-2554",
		"email": "bpendleton@wtamu.edu",
		"thumb": "/images/bonnie-pendleton-bodyphoto.jpg",
		"url": "/bonnie-pendleton",
		"expertise": "Entomology, Entomophagy, International Agriculture, Pest Management, and Plant Resistance"
	},
	{
		"name": "Dr. Brenda Fields Cross",
		"title": "Department Head and Instructor",
		"dep": "Communication Disorders, Department of",
		"building": "Virgil Henson Activities Center",
		"room": "242 X",
		"phone": " 806-651-5109",
		"email": "bcross@wtamu.edu",
		"thumb": "/images/brenda-cross-bodyphoto.jpg",
		"url": "/brenda-cross",
		"expertise": "A&amp;P for Hearing and Speech Sciences, Audiology, Aural Rehab, Balance, Communication Disorders, Dizziness, Hearing Loss, Professional Issues, and Tinnitus"
	},
	{
		"name": "Dr. Brock C. Blaser",
		"title": "Associate Professor of Plant Science",
		"dep": "Agricultural Sciences",
		"building": "Agriculture and Natural Sciences Building",
		"room": "114 L",
		"phone": "806-651-2555",
		"email": "bblaser@wtamu.edu",
		"thumb": "/images/brock-blaser-bodyphoto.jpg",
		"url": "/brock-blaser",
		"expertise": "Crop Production, Cropping Systems, Ecology, Physiology, and Plant and Soil Science"
	},
	{
		"name": "Dr. Bruce C. Brasington",
		"title": "Professor of History",
		"dep": "History, Department of",
		"building": "Old Main",
		"room": "403 C",
		"phone": "806-651-2426",
		"email": "bbrasington@wtamu.edu",
		"thumb": "/images/bruce-brasington-bodyphoto.jpg",
		"url": "/bruce-brasington",
		"expertise": "Church History to 1564, Codicology, Medieval Canon Law, Medieval History ,Medieval Latin, Medieval Latin Paleography, Naval History (particularly English): 1860&#8211;1918, and Roman History"
	},
	{
		"name": "Dr. Bryan Vizzini",
		"title": "Associate Professor of History",
		"dep": "History, Department of",
		"building": "Old Main",
		"room": "403 A",
		"phone": "806-651-2419",
		"email": "bavizzini@wtamu.edu",
		"thumb": "/images/bryan-vizzini-headphoto.jpg",
		"url": "/bryan-vizzini",
		"expertise": "Concept of Jihad, Taliban, and Threat of Terrorism Worldwide"
	},
	{
		"name": "Dr. Byron Pearson",
		"title": "Professor of History",
		"dep": "History, Department of",
		"building": "Old Main",
		"room": "324 A",
		"phone": "806-651-2430",
		"email": "bpearson@wtamu.edu",
		"thumb": "/images/byron-pearson-bodyphoto.jpg",
		"url": "/byron-pearson",
		"expertise": "American West, Environmental History, Legal and Constitutional History, Native American History, and U.S. History"
	},
	{
		"name": "Dr. Carolyn Bouma",
		"title": "Assistant Professor of Biology",
		"dep": "Life, Earth and Environmental Sciences, Department of ",
		"building": "Agriculture and Natural Sciences Building",
		"room": "341",
		"phone": "806-651-2569",
		"email": "cbouma@wtamu.edu",
		"thumb": "/images/carolyn-bouma-bodyshot.jpg",
		"url": "/carolyn-bouma",
		"expertise": "Biochemistry, General Biology, Infectious Diseases, and Microbiology"
	},
	{
		"name": "Dr. Cathy Clewett",
		"title": "Assistant Professor of Physics",
		"dep": "Chemistry and Physics, Department of ",
		"building": "Agriculture and Natural Sciences Building",
		"room": "114 G",
		"phone": "806-651-2545",
		"email": "cclewett@wtamu.edu",
		"thumb": "/images/cathy-clewett-bodyphoto.jpg",
		"url": "/cathy-clewett",
		"expertise": "Nuclear Magnetic Resonance Characterization of Materials"
	},
	{
		"name": "Dr. Charles M. Chase",
		"title": "Associate Professor of Sports and Exercise Sciences",
		"dep": "Sports and Exercise Sciences, Department of ",
		"building": "Virgil Henson Activities Center",
		"room": "231",
		"phone": " 806-651-2376",
		"email": "cchase@wtamu.edu",
		"thumb": "/images/charles-chase-bodyphoto.jpg",
		"url": "/charles-chase",
		"expertise": "Adventure Education, Archery, Camping Programs, Curriculum and Instruction, Outdoor Education, Outdoor Living and Wilderness Survival Skills, Pedagogy, and Recreation and Leisure Programming"
	},
	{
		"name": "Dr. Choong-ha Nam",
		"title": "Associate Professor of Music",
		"dep": "Music, School of",
		"building": "Sybil B. Harrington Fine Arts Complex",
		"room": "235",
		"phone": "806-651-2851",
		"email": "cnam@wtamu.edu",
		"thumb": "/images/choongha-nam-bodyphoto.jpg",
		"url": "/choongha-nam",
		"expertise": "Group Performance, Piano Pedagogy, Piano Performance, and Post-tonal Theory"
	},
	{
		"name": "Dr. Cloyce Kuhnert",
		"title": "Assocaite Professor of Voice",
		"dep": "Music, School of",
		"building": "Sybil B. Harrington Fine Arts Complex",
		"room": "212",
		"phone": "806-651-2856",
		"email": "ckuhnert@wtamu.edu",
		"thumb": "/images/cloyce-kuhnert-bodyphoto.jpg",
		"url": "/cloyce-kuhnert",
		"expertise": "Diction, Opera Workshop, Show Choir, Vocal Pedagogy, and Vocal Performance"
	},
	{
		"name": "Dr. Conn Thomas",
		"title": "Geneva Schaeffer Professor of Education and Social Sciences and  Director of The Center for Learning Disabilities",
		"dep": "Education, Department of",
		"building": "Old Main",
		"room": "215 C",
		"phone": "806-651-3632",
		"email": "cthomas@wtamu.edu",
		"thumb": "/images/conn-thomas-bodyphoto.jpg",
		"url": "/conn-thomas",
		"expertise": "Alternative Certification for Educators, Change Behavior and Strategic Planning, Curriculum and Instruction, Inclusion/Mainstreaming, Learning Strategies, Special Education, and Strategic Instruction"
	},
	{
		"name": "Mrs. Connie McKee",
		"title": "Instructor of Communication Studies and Director of Forensics",
		"dep": "Communication, Department of",
		"building": "Sybil B. Harrington Fine Arts Complex",
		"room": "191",
		"phone": " 806-651-2415",
		"email": "cmckee@wtamu.edu",
		"thumb": "/images/connie-mckee-bodyphoto.jpg",
		"url": "/connie-mckee",
		"expertise": "Communication Apprehension, Competitive Speech, Debate,Interpersonal Communication, Leadership, Persuasion, Public Speaking, Small Group Communication, Training and Development, and True Colors Certified"
	},
	{
		"name": "Dr. David Craig",
		"title": "Associate Professor of Physics",
		"dep": "Chemistry and Physics, Department of ",
		"building": "Agriculture and Natural Sciences Building",
		"room": "114 C",
		"phone": "806-651-5262",
		"email": "dcraig@wtamu.edu",
		"thumb": "/images/david-craig-bodyphoto.jpg",
		"url": "/daivd-craig",
		"expertise": "Physics"
	},
	{
		"name": "Dr. Darlene Pulliam ",
		"title": "Professor of Accounting",
		"dep": "Accounting, Economics and Finance",
		"building": "Classroom Center",
		"room": "215 E",
		"phone": "806-651-2521",
		"email": "dpulliam@wtamu.edu",
		"thumb": "/images/dpulliam.jpg",
		"url": "/Darlene Pulliam",
		"expertise": "Accounting"
	},
	{
		"name": "Dr. David R. Khan",
		"title": "Associate Professor of Biochemistry, Department Head, and Ross W. Wilson Chair in Chemistry",
		"dep": "Chemistry and Physics, Department of ",
		"building": "Chemistry and Physics Building",
		"room": "N/A",
		"phone": " 806-651-2547",
		"email": "dkhan@wtamu.edu",
		"thumb": "/images/david-khan-bodyshot.jpg",
		"url": "/david-khan",
		"expertise": "Cancer Research and Drug Delivery"
	},
	{
		"name": "Dr. David Lust",
		"title": "Associate Professor of Animal Science",
		"dep": "Agricultural Sciences",
		"building": "Agriculture and Natural Sciences Building",
		"room": "213 L",
		"phone": "806-651-2551",
		"email": "dlust@wtamu.edu",
		"thumb": "/images/david-lust-bodyshot.jpg",
		"url": "/david-lust",
		"expertise": "Animal Science, Artificial Insemination, Beef Cattle Management and Production, and Livestock Judging and Evaluation"
	},
	{
		"name": "Dr. De&apos;Arno De&apos;Armond",
		"title": "Associate Professor Finance",
		"dep": "Accounting, Economics and Finance",
		"building": "Classroom Center",
		"room": "214 C",
		"phone": "806-651-2490",
		"email": "ddearmond@wtamu.edu",
		"thumb": "/images/drarno_dearmond_bodyshot.jpg",
		"url": "/De-Arno De-Armond",
		"expertise": "Advertising, Financial Planning, Marketing, Risk Management, Sales, and Sales Management"
	},
	{
		"name": "Dr. Dean Hawkins",
		"title": "Dean, College of Agriculture and Natural Sciences",
		"dep": "Agriculture and Natural Sciences",
		"building": "Agriculture and Natural Sciences Building",
		"room": "213",
		"phone": "806-651-2563",
		"email": "dhawkins@wtamu.edu",
		"thumb": "/images/dean-hawkins-bodyshot.jpg",
		"url": "/dean-hawkins",
		"expertise": "Artificial Insemination, Fertility, and Reproductive Physiology"
	},
	{
		"name": "Dr. Deborah Davenport",
		"title": "Associate Department Head and Associate Professor of Nursing",
		"dep": "Nursing, Department of ",
		"building": "Old Main",
		"room": "313 A",
		"phone": "806-651-2637",
		"email": "ddavenport@wtamu.edu",
		"thumb": "/images/deborah-davenport-bodyphoto.jpg",
		"url": "/deborah-davenport",
		"expertise": "Advanced Cardiac Life Support (ACLS), Caring in Nursing, Coronary Care Nursing, Critical Care Nursing, Emergency Nursing, and Thermal Trauma"
	},
	{
		"name": "Mr. Don Lefevre",
		"title": "Associate Professor of Music and Director of Bands",
		"dep": "Music, School of",
		"building": "Mary Moody Northern Hall",
		"room": "1013",
		"phone": "806-651-2855",
		"email": "dlefevre@wtamu.edu",
		"thumb": "/images/don-lefevre-bodyphoto.jpg",
		"url": "/don-lefevre",
		"expertise": "Directing Bands and Saxophone"
	},
	{
		"name": "Dr. Douglas P. Bingham",
		"title": "Associate Dean of the College of Agriculture and Natural Sciences and Professor of Biology",
		"dep": "Life, Earth and Environmental Sciences, Department of ",
		"building": "Agriculture and Natural Sciences Building",
		"room": "106",
		"phone": "806-651-3570",
		"email": "dbingham@wtamu.edu",
		"thumb": "/images/douglas-bingham-bodyshot.jpg",
		"url": "/douglas-bingham",
		"expertise": "Biology of AIDS, Immunology, and Microbiology"
	},
	{
		"name": "Mr. Douglas Storey",
		"title": "Associate Professor of Music",
		"dep": "Music, School of",
		"building": "Mary Moody Northern Hall",
		"room": "258",
		"phone": "806-651-2836",
		"email": "dstorey@wtamu.edu",
		"thumb": "/images/douglas-storey-bodyphoto.jpg",
		"url": "/douglas-storey",
		"expertise": "Clarinet Performance and Pedagogy"
	},
	{
		"name": "Dr. Duane J. Rosa",
		"title": "Professor of Economics",
		"dep": "Accounting, Economics and Finance",
		"building": "Classroom Center",
		"room": "336 B",
		"phone": "806-651-2520",
		"email": "drosa@wtamu.edu",
		"thumb": "/images/duane-rosa-bodyphoto.jpg",
		"url": "/duane-rosa",
		"expertise": "Economic Planning, Energy Policy, Environmental Economics, Environmental Issues, Hazardous Materials Transportation, Oil and Gas Prices (including Price Gouging), Policy, Transportation Economics, Transportation Management, Transportation Systems and Security, Water Issues, and Water Resources"
	},
	{
		"name": "Dr. Edward P. Kahler II",
		"title": "Associate Dean of The Sybil B. Harrington of Fine Arts and Humanities, Interim Department Head and Associate Professor of The School of Music, and Director of Music Therapy",
		"dep": "Fine Arts and Humanities, Sybil B Harrington College of ",
		"building": "Mary Moody Northern Hall",
		"room": "161",
		"phone": "806-651-2776",
		"email": "ekahler@wtamu.edu",
		"thumb": "/images/edward-kahler-bodyphoto.jpg",
		"url": "/edward-kahler",
		"expertise": "Music Therapy, Music and Exceptional Children, and Research Methods in Music Education and Music Therapy"
	},
	{
		"name": "Mr. Edward R. Truitt",
		"title": "Associate Professor of Dance",
		"dep": "Art, Theatre and Dance",
		"building": "Mary Moody Northern Hall",
		"room": "153",
		"phone": "806-651-2820",
		"email": "etruitt@wtamu.edu",
		"thumb": "/images/edward-truitt-bodyphoto.jpg",
		"url": "/edward-truitt",
		"expertise": "Ballet and Jazz Dance Technique, Choreography, Dance History and Aesthetics, and Teaching Methods"
	},
	{
		"name": "Dr. Elizabeth Morrow Clark",
		"title": "Associate Professor of History",
		"dep": "History, Department of",
		"building": "Old Main",
		"room": "403 D",
		"phone": "806-651-2422",
		"email": "eclark@wtamu.edu",
		"thumb": "/images/elizabeth-clark-bodyphoto.jpg",
		"url": "/elizabeth-clark",
		"expertise": "1989 Revolutions, Balkans, Eastern Europe, Ethnic Cleansing, Former Soviet Union, Holocaust, Modern Germany, Poland, and Russia"
	},
	{
		"name": "Dr. Emily M. Hunt",
		"title": "Dean of The School of Engineering, Computer Science, and Mathematics, and Professor of Mechanical Engineering",
		"dep": "Engineering and Computer Science, and Mathematics, School of ",
		"building": "Engineering and Computer Science Building",
		"room": "112",
		"phone": "806-651-5257",
		"email": "ehuint@wtamu.edu",
		"thumb": "/images/emily-hunt-bodyphoto.jpg",
		"url": "/emily-hunt",
		"expertise": "Combustion, Materials Science, and Nanocomposite Energetic Materials"
	},
	{
		"name": "Dr. Emily S. Kinsky",
		"title": "Associate Professor of Mass Communication",
		"dep": "Communication, Department of",
		"building": "Fine Arts Complex",
		"room": "161",
		"phone": "806-651-2412",
		"email": "ekinsky@wtamu.edu",
		"thumb": "/images/emily-kinsky-bodyshot.jpg",
		"url": "/emily-kinsky",
		"expertise": "Advertising, Design, Media, and Public Relations"
	},
	{
		"name": "Dr. Enyonam Osei-Hwere",
		"title": "Assistant Professor of Mass Communication",
		"dep": "Communication, Department of",
		"building": "Sybil B. Harringtoni Fine Arts Complex",
		"room": "265",
		"phone": "806-651-2411",
		"email": "eosei-hwere@wtamu.edu",
		"thumb": "/images/enyonam-osei-hwere-bodyshot.jpg",
		"url": "/enyonam-osei-hwere",
		"expertise": "African Cultures and Diversity, Children and Media, Developing World Issues, Global Media/World Broadcasting, Global Media/World Change, HIV/AIDS in Africa, Learning Communities, Media for Social Change, Popular Culture, Poverty and Development, Student Leaders, Supervision and Advising Student Organizations, and Women and Media"
	},
	{
		"name": "Ernesto Martinez",
		"title": "Goat Herder",
		"dep": "Music",
		"building": "Old Main",
		"room": "222",
		"phone": "123-456-7890 x",
		"email": "eamartinez@wtmau.edu",
		"thumb": "/images/11_17wta006_sprngenrllmnt_websiteheader_1000x446_april01.jpg",
		"url": "/ernesto-martinez",
		"expertise": "Goats!, dogs, cats"
	},
	{
		"name": "Dr. E.W. Henderson",
		"title": "Dean of The College of Education and Social Sciences",
		"dep": "Education and Social Sciences, College of",
		"building": "Old Main",
		"room": "410 D",
		"phone": "806-651-2603",
		"email": "ehenderson@wtamu.edu",
		"thumb": "/images/ewhenderson-bodyphoto.jpg",
		"url": "/ew-henderson",
		"expertise": "Education Law"
	},
	{
		"name": "Dr. E.W. Henderson",
		"title": "",
		"dep": "",
		"building": "",
		"room": "",
		"phone": "123-456-7890 x",
		"email": "@example.edu",
		"thumb": "/",
		"url": "/_cascade/base-assets/faculty-staff",
		"expertise": ""
	},
	{
		"name": "Dr. Freddie J. Davis",
		"title": "Associate Professor of Mechanical Engineering",
		"dep": "Engineering and Computer Science, and Mathematics, School of ",
		"building": "Kilgore Research Center",
		"room": "117",
		"phone": "806-651-3530",
		"email": "fdavis@wtamu.edu",
		"thumb": "/images/freddie-davis-bodyphoto.jpg",
		"url": "/freddie-davis",
		"expertise": "Heat Transfer and Fluid Mechanics, Nuclear Engineering, and Risk and Decision Analysis"
	},
	{
		"name": "Dr. Gary C. Barbee",
		"title": "Associate Professor of Environmental Science",
		"dep": "Life, Earth and Environmental Sciences, Department of ",
		"building": "Agriculture and Natural Sciences Building",
		"room": "324",
		"phone": "806-651-2294",
		"email": "gbarbee@wtamu.edu",
		"thumb": "/images/gary-barbee-bodyphoto.jpg",
		"url": "/gary-barbee",
		"expertise": "Aquatic Toxicity, Bioremediation, Human and Ecological Exposure and Risk Assessment, Occupational and Environmental Toxicology, Regulatory Projects and Litigation, Remediation of Contaminated Soils, Surface and Ground Waters, and USEPA"
	},
	{
		"name": "Dr. Gary Bigham",
		"title": "Associate Professor of Education",
		"dep": "Education, Department of",
		"building": "Old Main",
		"room": "205 B",
		"phone": "806-651-3622",
		"email": "gbigham@wtamu.edu",
		"thumb": "/images/gary-bigham-bodyphoto.jpg",
		"url": "/gary-bigham",
		"expertise": "Educational Leadership, Effective Classroom Instruction, Online Instruction ,Principalship, Superintendency, and Vision and Mission Development"
	},
	{
		"name": "Dr. Gary D. Kelley",
		"title": "Professor of Computer Information Systems and Director of Instutional Research",
		"dep": "Engineering and Computer Science, and Mathematics, School of ",
		"building": "Classroom Center",
		"room": "214 A",
		"phone": "806-651-2495",
		"email": "gkelley@wtamu.edu",
		"thumb": "/images/gary-kelley-bodyphoto.jpg",
		"url": "/gary-kelley",
		"expertise": "Forecasting and Statistical Analysis"
	},
	{
		"name": "Dr. Gerald Chen",
		"title": "Associate Professor of Engineering Technology",
		"dep": "Engineering and Computer Science, and Mathematics, School of ",
		"building": "Engineering and Computer Science Building",
		"room": "106",
		"phone": "806-651-2449",
		"email": "gchen@mail.wtamu.edu",
		"thumb": "/images/gerald-chen-bodyphoto.jpg",
		"url": "/gerald-chen",
		"expertise": "Computer-Aided Design, Computer-Aided Manufacturing, Curriculum Development&#8212;Engineering/Industrial Technology, Electronics, Instrumentation, Quality Management, Statistical Quality Control, and Tech-Prep Education"
	},
	{
		"name": "Dr. Gerald E. Schultz",
		"title": "Professor of Geology",
		"dep": "Life, Earth and Environmental Sciences, Department of ",
		"building": "Agriculture and Natural Sciences Building",
		"room": "330",
		"phone": "806-651-2580",
		"email": "gschultz@wtamu.edu",
		"thumb": "/images/gerald-schultz-bodyphoto.jpg",
		"url": "/gerald-schultz",
		"expertise": "Fossil Mammals of the Texas Panhandle, Geology of Palo Duro Canyon, and Regional Geology and Paleontology"
	},
	{
		"name": "Mr. Gregg Lawler",
		"title": "Instructor of Mathematics",
		"dep": "Engineering and Computer Science, and Mathematics, School of ",
		"building": "Classroom Center",
		"room": "421 A",
		"phone": "806-651-2535",
		"email": "glawler@wtamu.edu",
		"thumb": "/",
		"url": "/gregg-lawler",
		"expertise": "Mathematics"
	},
	{
		"name": "Dr. Harry Hueston",
		"title": "Professor of Criminal Justice",
		"dep": "Political Science and Criminal Justice, Department of ",
		"building": "Old Main",
		"room": "408 B",
		"phone": "806-651-2421",
		"email": "hhueston@wtamu.edu",
		"thumb": "/images/harry-hueston-bodyphoto.jpg",
		"url": "/harry-hueston",
		"expertise": "Agro-Security Management, Agro-Terrorism, Crime Data, Criminal Justice in Mexico, Cyber Crimes, Emergency Management, Emergency management, Ethics, Homeland Security, Impacts of Technology and Social Media in Managing Crisis, Incident Command as It Relates to Law Enforcement, Internships in Criminal Justice, Israel and Palestine in Conflict, Law Enforcement, Managing Police Departments, Managing Police Departments, NIMS, Profiling, School Violence, Social Media, Terrorism,  and Terrorism Crisis Management"
	},
	{
		"name": "Dr. Helen Reyes",
		"title": "Department Head and Assistant Professor of Nursing",
		"dep": "Nursing, Department of ",
		"building": "Old Main",
		"room": "313 B",
		"phone": "806-651-2631",
		"email": "hreyes@wtamu.edu",
		"thumb": "/images/helen-reyes-bodyphoto.jpg",
		"url": "/helen-reyes",
		"expertise": "Adult Health, Gerontology ,Home Health, Nursing Fundamentals, and Pharmacology"
	},
	{
		"name": "Dr. James Owens",
		"title": "Professor of Finance and Hodges Professor of Corporate Governance",
		"dep": "Accounting, Economics and Finance",
		"building": "Classroom Center",
		"room": "215 A",
		"phone": "806-651-2519",
		"email": "jowens@wtamu.edu",
		"thumb": "/images/james-owens-bodyshot.jpg",
		"url": "/james-owens",
		"expertise": "Bank Management, Corporate Finance, and International Finance"
	},
	{
		"name": "Dr. James D. Woodyard",
		"title": "Professor of Chemisty",
		"dep": "Chemistry and Physics, Department of ",
		"building": "Chemistry and Physics Building",
		"room": "N/A",
		"phone": "806-651-2534",
		"email": "jwoodyard@wtamu.edu",
		"thumb": "/images/james-woodyard-headphoto.jpg",
		"url": "/james-woodyard",
		"expertise": "Organic Chemistry and Stereochemistry"
	},
	{
		"name": "Dr. Jean A. Stuntz",
		"title": "Associate Professor of History",
		"dep": "History, Department of",
		"building": "Old Main",
		"room": "405 B",
		"phone": "806-651-2409",
		"email": "jstuntz@wtamu.edu",
		"thumb": "/images/jean-stuntz-bodyphoto.jpg",
		"url": "/jean-stuntz",
		"expertise": "Local History, Spanish Empire in North America, Texas History, and U.S. Women&apos;s History"
	},
	{
		"name": "Dr. Jenifer Kunz",
		"title": "Department Head of Psychology, Sociology and Social Work and Associate Professor of Sociology",
		"dep": "Psychology, Sociology and Social Work, Department of",
		"building": "Old Main",
		"room": "429",
		"phone": "806-651-2597",
		"email": "jkunz@wtamu.edu",
		"thumb": "/images/jenifer-kunz-bodyphoto.jpg",
		"url": "/jenifer-kunz",
		"expertise": "Complex Organizations ,Family Sociology, Gender Issues, How to Explain War and Terrorism to Children, How to Explain War/Terrorism to Children, Prejudice/Discrimination Issues, and Race/Ethnic Relations"
	},
	{
		"name": "Dr. Jessica S. Mallard",
		"title": "Professor of Communication Studies and Dean of the Sybil B. Harrington College of Fine Arts and Humanities",
		"dep": "Fine Arts and Humanities, Sybil B Harrington College of ",
		"building": "Mary Moody Northern Hall",
		"room": "161",
		"phone": " 806-651-2777",
		"email": "jmallard@wtamu.edu",
		"thumb": "/images/jessica-mallard-bodyphoto.jpg",
		"url": "/jessica-mallard",
		"expertise": "Gender Communication, Research Methods, Rhetorical Criticism, and Service Learning"
	},
	{
		"name": "Mr. Joel Babitzke",
		"title": "Instructor of Biology",
		"dep": "Life, Earth and Environmental Sciences, Department of ",
		"building": "Agriculture and Natural Sciences Building",
		"room": "342",
		"phone": "806-651-3871",
		"email": "jbabitzke@wtamu.edu",
		"thumb": "/",
		"url": "/joel-babitzke",
		"expertise": "Comparative Anatomy, General Biology, Limnology, Turtle Ecology, Wildlife Conservation, and Zoology"
	},
	{
		"name": "Mr. John Landon",
		"title": "Professor of Theatre",
		"dep": "Art, Theatre and Dance",
		"building": "Sybil B. Harrington Fine Arts Complex",
		"room": "122",
		"phone": "806-651-2815",
		"email": "jlandon@wtamu.edu",
		"thumb": "/images/john-landon-headphoto.jpg",
		"url": "/john-landon",
		"expertise": "Scenic Construction, Stage Management, and Technical Theatre"
	},
	{
		"name": "Dr. John Pipkin",
		"title": "Equine Program Director, Regents Professor of Animal Science ",
		"dep": "Agricultural Sciences",
		"building": "Agriculture and Natural Sciences Building",
		"room": "213 C",
		"phone": "806-651-2557",
		"email": "jpipkin@wtamu.edu",
		"thumb": "/images/john-pipkin-bodyshot.jpg",
		"url": "/john-pipkin",
		"expertise": "Animal Science, Artificial Insemination, Beef Cattle Management and Production, and Livestock Judging and Evaluation"
	},
	{
		"name": "Dr. John David Rausch, Jr.",
		"title": "Teel Bivins Professor of Political Science",
		"dep": "Political Science and Criminal Justice, Department of ",
		"building": "Old Main",
		"room": "404 C",
		"phone": "806-651-2423",
		"email": "jrausch@wtamu.edu",
		"thumb": "/images/john-david-rausch-bodyphoto.jpg",
		"url": "/john-rausch ",
		"expertise": "Campaigns and Elections, Congress, Direct Democracy, Distance Learning, European Politics, General American Government, Politics and History of East and East Central Europe, Polls and Survey, Religion and Politics, and Texas State and Local Government"
	},
	{
		"name": "Dr. Joseph C. Cepeda",
		"title": "Professor of Geology",
		"dep": "Life, Earth and Environmental Sciences, Department of ",
		"building": "Agriculture and Natural Sciences Building",
		"room": "322",
		"phone": "806-651-2584",
		"email": "jcepeda@wtamu.edu",
		"thumb": "/images/joseph-cepeda-bodyphoto.jpg",
		"url": "/joseph-cepeda",
		"expertise": "Geochemistry, Geology of Western North America, and Volcanology"
	},
	{
		"name": "Dr. Keith Redpath",
		"title": "Harrington Lecturer in Violin",
		"dep": "Music, School of",
		"building": "Mary Moody Northern Hall",
		"room": "143",
		"phone": "806-651-2823",
		"email": "kredpath@wtamu.edu",
		"thumb": "/images/keith-redpath-bodyphoto.jpg",
		"url": "/keith-redpath",
		"expertise": "Chamber Music and Violin Performance "
	},
	{
		"name": "Mr. Kenneth Starcher",
		"title": "Assistant Director of Alternative Energy Institute and Instrcutor of ECSM",
		"dep": "Engineering and Computer Science, and Mathematics, School of ",
		"building": "Kilgore Research Center",
		"room": "119",
		"phone": "806-651-2296",
		"email": "kstarcher@wtamu.edu",
		"thumb": "/images/kenneth-starcher-headshot.jpg",
		"url": "/kenneth-starcher",
		"expertise": "Data Collection/Analysis, Education Outreach, Renewable Energy Tours/Wind Test Center, Solar Energy, Wind Energy, and Wind Turbine Installation"
	},
	{
		"name": "Dr. Kristian Gill",
		"title": "Assistant Professor of Mathematics",
		"dep": "Engineering and Computer Science, and Mathematics, School of ",
		"building": "Classroom Center",
		"room": "417 A",
		"phone": "806-651-5238",
		"email": "kgill@wtamu.edu",
		"thumb": "/images/kristina-gill-bodyphoto.jpg",
		"url": "/kristian-gill",
		"expertise": "EC-12 Mathematics Content, Online Mathematics Success, Student Attitude and Motivation, and Teaching Mathematics Conceptually"
	},
	{
		"name": "Dr. Kristina D. Drumheller",
		"title": "Associate Professor of Communication Studies and Interim Department Head of History",
		"dep": "Communication, Department of",
		"building": "Sybil B. Harringtoni Fine Arts Complex",
		"room": "192",
		"phone": "806-651-2816",
		"email": "kdrumheller@wtamu.edu",
		"thumb": "/images/kristina-drumheller-bodyphoto.jpg",
		"url": "/kristina-drumheller",
		"expertise": "Crisis Communication, Diversity, LGBTQIA Communities, Media Rhetoric and Effects, Organizational Communication, Religious Communication, and Workplace Emotions and Spirituality"
	},
	{
		"name": "Dr. Lal K. Almas",
		"title": "Associate Dean of Agricultural and Natural Sciences",
		"dep": "Agricultural Sciences",
		"building": "Agricultural and Natural Sciences Building",
		"room": "106",
		"phone": "806-651-2552",
		"email": "lalmas@wtamu.edu",
		"thumb": "/images/lal-almas-bodyshot.jpg",
		"url": "/Lal-Almas",
		"expertise": "Agricultural Business and Economics, Agricultural Marketing and International Trade, Econometrics and Statistics, Financial Management, Production and Resource Economics, and Water Management and Planning"
	},
	{
		"name": "Dr. Lance Baker",
		"title": "Associate Professor of Animal Science",
		"dep": "Agricultural Sciences",
		"building": "Agriculture and Natural Sciences Building",
		"room": "213",
		"phone": "806-651-2561",
		"email": "lbaker@wtamu.edu",
		"thumb": "/images/lance-baker-bodyshot.jpg",
		"url": "/lance-baker",
		"expertise": "Animal Nutrition, Equine Exercise Physiology, Equine Nutrition and Physiology, and Equine Selection and Evaluation"
	},
	{
		"name": "Dr. Lance T. Kieth",
		"title": "Department Head and Professor of Agricultural Sciences",
		"dep": "Agricultural Sciences",
		"building": "Agriculture and Natural Sciences Building",
		"room": "213 B",
		"phone": "806-651-2556",
		"email": "lkieth@wtamu.edu",
		"thumb": "/images/lance-kieth-bodyphoto.jpeg",
		"url": "/lance-kieth",
		"expertise": "4-H/FFA Teaching Method, Extension Education, Teaching Education, and Youth Leadership"
	},
	{
		"name": "Mrs. Laura Waight",
		"title": "Instructor of Nursing",
		"dep": "Nursing, Department of ",
		"building": "Old Main",
		"room": "308 D",
		"phone": "806-651-2643",
		"email": "lwaight@wtamu.edu",
		"thumb": "/images/laura-waight-headphoto.jpg",
		"url": "/laura-waight",
		"expertise": "Critical Care Nursing, Medical Surgical Nursing, and Pathophysiology"
	},
	{
		"name": "Dr. LaVelle H. Mills",
		"title": "Associate Dean of Graduate Programs for The College of Business and Professor of Management",
		"dep": "Management, Marketing and General Business, Deptartment of",
		"building": "Classroom Center",
		"room": "210 B",
		"phone": "806-651-3866",
		"email": "lmills@wtamu.edu",
		"thumb": "/images/lavelle-mills-bodyphoto.jpg",
		"url": "/lavelle-mills",
		"expertise": "Employee Satisfaction and Productivity, Human Resource Management, and Sales Effectiveness Training"
	},
	{
		"name": "Dr. Leslie Ramos Salazar",
		"title": "Assistant Professor of Business Communication and Decision Management",
		"dep": "Management, Marketing and General Business, Deptartment of",
		"building": "Classroom Center",
		"room": "208 A",
		"phone": "806-651-2548",
		"email": "lsalazar@wtamu.edu",
		"thumb": "/images/leslie-ramos-salazar-bodyshot.jpg",
		"url": "/leslie-ramos-salazar",
		"expertise": "Business and Professional Communication, Civil Dialogue, Compassion and Human Emotion, Conflict Management, Cyberbullying, Family Relationships, HIV/AIDS Campaign Interventions, HIV/AIDS Prevention, HIV/AIDS and College Students, Health Communication, Human Relationships, Intercultural Conflict Management, Interpersonal Communication, Marital Relationships, Minority Health, Minority Health Disparities, Mother-Daughter Communication, Persuasion, Persuasive Speaking, Public Speaking, Relational Communication, Relationship Satisfaction, and Research Methods"
	},
	{
		"name": "Dr. Lisa A. Davis",
		"title": "Associate Department Head and Associate Professor of Nursing",
		"dep": "Nursing, Department of ",
		"building": "Old Main",
		"room": "308 E",
		"phone": "806-651-2641",
		"email": "ldavis@wtamu.edu",
		"thumb": "/images/lisa-davis-bodyphoto.jpg",
		"url": "/lisa-davis",
		"expertise": "Epidemiology, Holistic Care, Patient Expectations of Care, Qualitative Methodologies, Stress Management, Teaching/Learning Theory, and Theoretical Framework of Nursing Care"
	},
	{
		"name": "Mrs. Lorna R. Strong",
		"title": "Department Head and Instructor of Sports and Exercise Sciences and ATEP Program Director",
		"dep": "Sports and Exercise Sciences, Department of ",
		"building": "Virgil Henson Activities Center",
		"room": "217",
		"phone": "806-651-2382",
		"email": "lstrong@wtamu.edu",
		"thumb": "/images/lorna-strong-bodyphoto.jpg",
		"url": "/lorma-strong",
		"expertise": "Athletic Training, Sports Injuries, and Sports Medicine"
	},
	{
		"name": "Dr. Marietta Branson",
		"title": "Assistant Professor of Nursing and Associate Department Head of Nursing",
		"dep": "Nursing, Department of ",
		"building": "Old Main",
		"room": "311 B",
		"phone": "806-651-2634",
		"email": "mbranso@wtamu.edu",
		"thumb": "/images/marietta-branson-bodyphoto.jpg",
		"url": "/marietta-branson",
		"expertise": "Legal Nurse Consulting, Nursing Administration, and Obstetrical Nursing"
	},
	{
		"name": "Dr. Mark A. Bartley",
		"title": "Associate Professor of Music and Director of Orchestral Activities",
		"dep": "Music, School of",
		"building": "Mary Moody Northern Hall",
		"room": "257",
		"phone": "806-651-2830",
		"email": "mbartley@wtamu.edu",
		"thumb": "/images/mark-bartley-bodyphoto.jpg",
		"url": "/mark-bartley",
		"expertise": " Conducting Instrumental and Vocal Ensembles"
	},
	{
		"name": "Dr. Mark R. Riney",
		"title": "Associate Professor of Edcuation",
		"dep": "Education, Department of",
		"building": "Old Main",
		"room": "442",
		"phone": "806-651-2621",
		"email": "mriney@wtamu.edu",
		"thumb": "/images/mark-riney-bodyphoto.jpg",
		"url": "/mark-riney",
		"expertise": "Educational Psychology, Foundations, History of Education, and Multicultural Education"
	},
	{
		"name": "Dr. Martin M. Jacobsen",
		"title": "Associate Professor of English",
		"dep": "English, Philosophy, and Modern Languages, Department of ",
		"building": "Classroom Center",
		"room": "319 F",
		"phone": "806-651-2460",
		"email": "mjacobsen@wtamu.edu",
		"thumb": "/images/martin-jacobsen-bodyphoto.jpg",
		"url": "/martin-jacobsen",
		"expertise": "English Language, Linguistics, and Rhetoric"
	},
	{
		"name": "Dr. Marty Kuhlman",
		"title": "Associate Professor of History",
		"dep": "History, Department of",
		"building": "Old Main",
		"room": "403 B",
		"phone": "806-651-2420",
		"email": "mkuhlman@wtamu.edu",
		"thumb": "/images/marty-kuhlman-bodyphoto.jpg",
		"url": "/marty-kuhlman",
		"expertise": "Civil Rights, Civil War History, and Southern History"
	},
	{
		"name": "Mrs. Mary Jane Cruz",
		"title": "Instructor of Mathematics",
		"dep": "Engineering and Computer Science, and Mathematics, School of ",
		"building": "Classroom Center",
		"room": "421 C",
		"phone": "806-651-2537",
		"email": "mcruz@wtamu.edu",
		"thumb": "/images/mary-cruz-bodyphoto.jpg",
		"url": "/mary-cruz",
		"expertise": "Mathematics Education and Use of Technology in Math Classes"
	},
	{
		"name": "Dr. Matt Jackson",
		"title": "Associate Dean of The School of Engineering, Computer Science, and Mathematics and Bell Helicopter Professor of Mechanical Engineering",
		"dep": "Engineering and Computer Science, and Mathematics, School of ",
		"building": "Engineering and Computer Science Building",
		"room": "121",
		"phone": "806-651-2451",
		"email": "mjackson@wtamu.edu",
		"thumb": "/images/matt-jackson-bodyphoto.jpg",
		"url": "/matt-jackson",
		"expertise": "Combustion, Material Science, Solid Modeling, Thermal Modeling, and Thermal/Mechanical Design"
	},
	{
		"name": "Mr. Michael J. Knox",
		"title": "Vice President for Student Affairs",
		"dep": "Student Affairs",
		"building": "Jack B. Kelly Student Center",
		"room": "102 K",
		"phone": "806-651-2050",
		"email": " mknox@wtamu.edu",
		"thumb": "/images/michael-knox-headshot.jpg",
		"url": "/michael-knox",
		"expertise": "Behavioral Intervention Team, and Student Success Initiatives"
	},
	{
		"name": "Dr. Michelle L. Bartlett",
		"title": "Assistant Professor of Sports and Exercise Sciences",
		"dep": "Sports and Exercise Sciences, Department of ",
		"building": "Virgil Henson Activities Center",
		"room": "232",
		"phone": "806-651-2686",
		"email": "mbartlett@wtamu.edu",
		"thumb": "/images/michelle-bartlett-bodyphoto.jpg",
		"url": "/michelle-bartlett",
		"expertise": "Exercise Psychology, Nursing and Medical, Physical Education, Psychology of Physical Activity, Recreation and Leisure, and Sport Psychology"
	},
	{
		"name": "Dr. Monica Smith Hart",
		"title": "Assistatn Professor of English and Director of The Office of Writing Programs",
		"dep": "English, Philosophy, and Modern Languages, Department of ",
		"building": "Classroom Center",
		"room": "319 J",
		"phone": "806-651-2477",
		"email": "mhart@wtamu.edu",
		"thumb": "/images/monica-hart-bodyphoto.jpg",
		"url": "/monica-hart",
		"expertise": "British Literature and Culture, Literature,  and Poetry"
	},
	{
		"name": "Dr. Neil R. Meredith",
		"title": "Dana Professor of Business and Associate Professor of Economics",
		"dep": "Accounting, Economics and Finance",
		"building": "Classroom Center",
		"room": "222 F",
		"phone": "806-651-2493",
		"email": "nmeredith@wtamu.edu",
		"thumb": "/images/neil-meredith-bodyphoto.jpg",
		"url": "/neil-meredith",
		"expertise": "Health Economics, Industrial Organization and Regulation, International Economics, and Labor Economics"
	},
	{
		"name": "Dr. Neil Terry",
		"title": "Dean of The College of Business and Professor of Economics",
		"dep": "Accounting, Economics and Finance",
		"building": "Classroom Center",
		"room": "216 A",
		"phone": "806-651-2530",
		"email": "nterry@wtamu.edu",
		"thumb": "/images/neil-terry-bodyphoto.jpg",
		"url": "/neil-terry",
		"expertise": "Business Education, Industrial Organization, International Economics, and Labor Economics"
	},
	{
		"name": "Dr. R. Nicholas Gerlich",
		"title": "Hickman Professor of Marketing",
		"dep": "Management, Marketing and General Business, Deptartment of",
		"building": "Classroom Center",
		"room": "213 E",
		"phone": "806-651-2492",
		"email": "ngerlich@wtamu.edu",
		"thumb": "/images/nicholas-gerlich-bodyphoto.jpg",
		"url": "/nicholas-gerlich",
		"expertise": "Church Marketing, Course Development and Delivery Via the Internet, E-Commerce, Grocery Retailing, Home-Based Businesses, Internet Marketing, Marketing to Minorities, Mega-Churches, Small Businesses, Soft Drink Industry, Sporting Goods Industry/Sports Marketing, The Emerging Church, The Internet, Web Commerce, and Web Design"
	},
	{
		"name": "Dr. Nicholas A. Scales",
		"title": "Assistant Professor of Double Bass",
		"dep": "Music, School of",
		"building": "Mary Moody Northern Hall",
		"room": "256",
		"phone": "806-651-2849",
		"email": "nscales@wtamu.edu",
		"thumb": "/images/nicholas-scales-bodyphoto.jpg",
		"url": "/nicholas-scales",
		"expertise": "Chamber Music, Double Bass Performance and Pedagogy ,Jazz Band, Jazz Bass, Music Appreciation, Music Theory, and String Pedagogy"
	},
	{
		"name": "Dr. Nick Flynn",
		"title": "Professor of Biochemistry",
		"dep": "Chemistry and Physics, Department of ",
		"building": "Kilgore Research Center",
		"room": "145",
		"phone": "806-651-2542",
		"email": "nflynn@wtamu.edu",
		"thumb": "/images/nick-flynn-bodyshot.jpg",
		"url": "/nick-flynn",
		"expertise": "Food Chemistry, HPLC Analysis, and Nutritional Biochemistry"
	},
	{
		"name": "Dr. Pamela Lockwood",
		"title": "Associate Dean of The School of Engineering, Computer Science, and Mathematics and Professor of Mathematics",
		"dep": "Engineering and Computer Science, and Mathematics, School of ",
		"building": "Classroom Center",
		"room": "417 C",
		"phone": "806-651-2536",
		"email": "plockwood@wtamu.edu",
		"thumb": "/images/pamela-lockwood-bodyphoto.jpg",
		"url": "/pamela-lockwood",
		"expertise": " Mathematical Modeling of Biological Systems and Mathematical Statistics"
	},
	{
		"name": "Dr. Patricia Tyrer",
		"title": "Associate Professor of English",
		"dep": "English, Philosophy, and Modern Languages, Department of ",
		"building": "Classroom Center",
		"room": "319 G",
		"phone": "806-651-2476",
		"email": "ptyrer@wtamu.edu",
		"thumb": "/images/pat-tyrer-bodyphoto.jpg",
		"url": "/pat-tyrer",
		"expertise": "American Literature, American Modernism, Composition Studies, Composition Theory, Composition and Rhetoric, Computers and Writing, Contemporary Latin American Literature, Creative Non-Fiction, Creative Writing, Distance Education, Editing Film Studies, English Language ,Fiction, Film Studies, Literary Theory, Modernist Period (1890 -1950), Poetry, Pop Culture ,Prose, Technical &amp; Professional Communication, Technical Communication, Technical Writing, Women&apos;s Studies, and Writing"
	},
	{
		"name": "Dr. Paul H. Clark",
		"title": "Professor of History",
		"dep": "History, Department of",
		"building": "Old Main",
		"room": "402 E",
		"phone": "806-651-2425",
		"email": "pclark@wtamu.edu",
		"thumb": "/images/paul-clark-bodyphoto.jpg",
		"url": "/paul-clark",
		"expertise": "China, Education in East Asia, History of Language, Japan, Korea, and Medieval Japan (Samurai Era)"
	},
	{
		"name": "Mrs. Paula S. Schlegel",
		"title": "Instructor of Speech Communication",
		"dep": "Communication, Department of",
		"building": "Sybil B. Harrington Fine Arts Complex",
		"room": "111",
		"phone": "806-651-2796",
		"email": "pschlegel@wtamu.edu",
		"thumb": "/images/paula-schlegel-bodyphoto.jpg",
		"url": "/paula-schlegel",
		"expertise": "Communication and Listening, Gender, Healthy Conflict, Parenting, and Storytelling"
	},
	{
		"name": "Dr. Rajan Alex",
		"title": "Professor of Computer Science",
		"dep": "Engineering and Computer Science, and Mathematics, School of ",
		"building": "Engineering and Computer Science Building",
		"room": "145",
		"phone": "806-651-2288",
		"email": "ralex@wtamu.edu",
		"thumb": "/images/rajan-alex-bodyphoto.jpg",
		"url": "/rajan-alex",
		"expertise": "Fuzzy Logic Applications, Neural Networks, and Numerical Analysis"
	},
	{
		"name": "Mr. Randall J. Ray",
		"title": "Assistant Lecturer of Communication Studies and Director of Broadcast Engineering",
		"dep": "Communication, Department of",
		"building": "Sybil B. Harrington Fine Arts Complex",
		"room": "162",
		"phone": "806-651-2807",
		"email": "rray@wtamu.edu",
		"thumb": "/images/randy-ray-bodyphoto.jpg",
		"url": "/randall-ray",
		"expertise": "Broadcast Technology, Feature Writing, Media Convergence, Media Management, Recording Industry, and Recording Technology"
	},
	{
		"name": "Dr. Randy Combs",
		"title": "Associate Professor of Mathematics",
		"dep": "Engineering and Computer Science, and Mathematics, School of ",
		"building": "Classroom Center",
		"room": "417 E",
		"phone": "806-651-2532",
		"email": "rcombs@wtamu.edu",
		"thumb": "/",
		"url": "/randy-combs",
		"expertise": "Analytic Number Theory and Fourier Analysis on Euclidean Spaces"
	},
	{
		"name": "Dr. Reed L. Welch",
		"title": "Associate Professor of Political Science",
		"dep": "Political Science and Criminal Justice, Department of ",
		"building": "Old Main",
		"room": "414 B",
		"phone": "806-651-2433",
		"email": "rlwelch@wtamu.edu",
		"thumb": "/images/reed-welch-bodyphoto.jpg",
		"url": "/reed-welch",
		"expertise": "American Government and Politics, Campaigns and Elections, Interest Groups, Political Parties, Public Opinion and Voting Behavior, Texas Government, and The American Presidency"
	},
	{
		"name": "Mr. Rick Haasl",
		"title": "Assistant to The Dean of The College of Nursing and Health Sciences and Instructor of Sports and Exercise Sciences",
		"dep": "Nursing and Health Sciences, College of  ",
		"building": "Old Main",
		"room": "402 C",
		"phone": "806-651-3502",
		"email": "rhaasl@wtamu.edu",
		"thumb": "/images/rick-haasl-headphoto.jpg",
		"url": "/rick-haasl",
		"expertise": "Leadership, Education, and Stress Management "
	},
	{
		"name": "Dr. Robert E. DeOtte Jr.",
		"title": "Professor of Civil and Environmental Engineering ",
		"dep": "Engineering and Computer Science, and Mathematics, School of ",
		"building": "Engineering and Computer Science Building",
		"room": "120",
		"phone": "806-651-8781",
		"email": "rdeotte@wtamu.edu",
		"thumb": "/images/robert-deotte-bodyphoto.jpg",
		"url": "/robert-deotte",
		"expertise": "Aerosol Mechanics, Agricultural Disaster Planning, Agricultural Disaster Preparedness, Agrosecurity Mediation, Agroterrorism, Air Pollution Control, Bio-Terrorism, CAFO Security and Response, Emergency Management, Emergency Planning, Engineering Ethics, Ethics, Fluid Mechanics, Fly Ash Disposal and Utilization, Hydraulics, Hydrology, Industry Government Relationships in Disaster Planning, Industry Participation in Disaster Planning, and Monitoring Biological Aerosols"
	},
	{
		"name": "Dr. Robert Hansen",
		"title": "Department Head of The Department of Art, Theatre, and Dance, Director of The School of Music, and Regents Professor of Music",
		"dep": "Music, School of",
		"building": "Sybil B. Harrington Fine Arts Complex",
		"room": "214 or 103",
		"phone": "806-651-2850 or 2811",
		"email": "rhansen@wtamu.edu",
		"thumb": "/images/robert-hansen-bodyphoto.jpg",
		"url": "/robert-hansen",
		"expertise": "Opera and Musical Theater Performance and Direction, Vocal Pedagogy and Physiology, and Voice Performance"
	},
	{
		"name": "Dr. Robert J. Krause",
		"title": "Professor of Oboe",
		"dep": "Music, School of",
		"building": "Mary Moody Northern Hall",
		"room": "136",
		"phone": "806-651-2821",
		"email": "rkrause@wtamu.edu",
		"thumb": "/images/robert-krause-bodyphoto.jpg",
		"url": "/robert-krause",
		"expertise": "Critique and History of Opera, Music Theory, Oboe Performance and Pedagogy, and Oboe Reed-Making and Pedagogy"
	},
	{
		"name": "Dr. Rocky Ward",
		"title": "Assistant Professor of Biology",
		"dep": "Life, Earth and Environmental Sciences, Department of ",
		"building": "Agriculture and Natural Sciences Building",
		"room": "343",
		"phone": "806-651-2283",
		"email": "rward@wtamu.edu",
		"thumb": "/images/rocky-ward-bodyshot.jpg",
		"url": "/rocky-ward",
		"expertise": "Conservation Genetics, Evolutionary Biology, and Vertebrate Biology"
	},
	{
		"name": "Dr. Roy J. Issa",
		"title": "Associate Professor of Mechanical Engineering",
		"dep": "Engineering and Computer Science, and Mathematics, School of ",
		"building": "Engineering and Computer Science Building",
		"room": "103",
		"phone": "806-651-5261",
		"email": "rissa@wtamu.edu",
		"thumb": "/images/roy-issa-bodyphoto.jpg",
		"url": "/roy-issa",
		"expertise": "Modeling, Multiphase Flow, Newtonian and Non-Newtonian Fluids, Simulation and Experiments in the areas of Heat Transfer and Fluid Dynamics that include Single Phase"
	},
	{
		"name": "Mr. Robert R. Brantley",
		"title": "Regents Professor of Theatre - Acting, Directing, and Theatre History and Director of Theatre",
		"dep": "Art, Theatre and Dance",
		"building": "Sybil B. Harrington Fine Arts Complex",
		"room": "123",
		"phone": "806-651-2813",
		"email": "rbrantley@wtamu.edu",
		"thumb": "/images/royal-brantley-headphoto.jpg",
		"url": "/royal-brantley",
		"expertise": "Acting, Directing, Production, Stage Combat, Theatre History, and Voice and Dialect"
	},
	{
		"name": "Dr. Russ Teweleit",
		"title": "Associate Professor of Music, Associate Director of Bands, and Coordinator of Music Education",
		"dep": "Music, School of",
		"building": "Mary Moody Northern Hall",
		"room": "260 N",
		"phone": "806-651-2863",
		"email": "rteweleit@wtamu.edu",
		"thumb": "/images/russ-teweleit-bodyphoto.jpg",
		"url": "/russ-teweleit",
		"expertise": "Band, Jazz Studies, Music Education, and Student-Teacher Supervision"
	},
	{
		"name": "Mrs. Sandra Vance Davidson",
		"title": "Instructor of Spanish",
		"dep": "English, Philosophy, and Modern Languages, Department of ",
		"building": "Classroom Center",
		"room": "320 C",
		"phone": "806-651-2463",
		"email": "sdavidson@wtamu.edu",
		"thumb": "/images/sanda-davidson-bodyphoto.jpg",
		"url": "/sandra-davidson",
		"expertise": "Spanish Grammar"
	},
	{
		"name": "Dr. Sang K. Hwang",
		"title": "Associate Professor of Education",
		"dep": "Education, Department of",
		"building": "Old Main",
		"room": "447",
		"phone": "806-651-2617",
		"email": "shwang@wtamu.edu",
		"thumb": "/images/sang-hwang-bodyphoto.jpg",
		"url": "/sang-hwang",
		"expertise": "America Reads Program, Field-Based Course, Reading, and Reading Assessment"
	},
	{
		"name": "Mr. Scott S. Frish",
		"title": "Associate Professor of Art",
		"dep": "Art, Theatre and Dance",
		"building": "Mary Moody Northen Hall",
		"room": "270",
		"phone": "806-651-2793",
		"email": "sfrish@wtamu.edu",
		"thumb": "/images/scott-frish-bodyshot.jpg",
		"url": "/scott-frish",
		"expertise": "2-D Design, Digital Art, Drawing, and Printmaking"
	},
	{
		"name": "Dr. Shiquan Tao",
		"title": "Associate Professor of Chemistry",
		"dep": "Chemistry and Physics, Department of ",
		"building": "Kilgore Research Center",
		"room": "137",
		"phone": "806-651-2539",
		"email": "stao@wtamu.edu",
		"thumb": "/images/shiquan-tao-bodyshot.jpg",
		"url": "/shiquan-tao",
		"expertise": "Food Safety and Medical Applications and Sensor Technology for Environmental Monitoring"
	},
	{
		"name": "Dr. Stephen E. Severn",
		"title": "Professor of English; Department Head, English, Philosophy and Modern Languages",
		"dep": "English, Philosophy, and Modern Languages, Department of ",
		"building": "Classroom Center",
		"room": "324 A",
		"phone": "806-651-2475",
		"email": "ssevern@wtamu.edu",
		"thumb": "/images/stephen-severn-bodyshot.jpg",
		"url": "/stephen-severn",
		"expertise": "British Literature, Business Writing, Contingency/Disaster Recovery Planning, Institutional Assessment, Teaching Writing Rhetoric, Technical Writing, and Visual Literacy"
	},
	{
		"name": "Mrs. Susan L. Allen",
		"title": "Assistant Vice President for Academic Affairs",
		"dep": "Academic Affairs",
		"building": "Old Main",
		"room": "307 D",
		"phone": "806-651-2044",
		"email": "sallen@wtamu.edu",
		"thumb": "/images/susan-allen-headphoto.jpg",
		"url": "/susan-allen",
		"expertise": "Alternative Teacher Certification, Compliance with State and Federal Regulations Regarding Educator Preparation, Education Traditional and Alternative Teacher Certification, and Educator Preparation,Teacher Certification"
	},
	{
		"name": "Dr. Susan Martin Tariq",
		"title": "Professor of Music",
		"dep": "Music, School of",
		"building": "Mary Moody Northern Hall",
		"room": "1001",
		"phone": "806-651-2838",
		"email": "stariq@wtamu.edu",
		"thumb": "/images/susan-tariq-bodyphoto.jpg",
		"url": "/susan-tariq",
		"expertise": "Band, Jazz Studies, Music Education, and Student Teacher Supervision"
	},
	{
		"name": "Dr. Syed Tariq Anwar",
		"title": "Professor of Marketing",
		"dep": "Management, Marketing and General Business, Deptartment of",
		"building": "Classroom Center",
		"room": "213 F",
		"phone": "806-651-2491",
		"email": "sanwar@wtamu.edu",
		"thumb": "/images/syed-anwar-bodyphoto.jpg",
		"url": "/syed-anwar",
		"expertise": "E-Business/E-Commerce, Global Markets, Global/Multinational Corporations, International Business, International Business and Trade, International Marketing, Internet-Related Global Strategy Industries, Internet-Related Industries, Social Mind Set and Customs of Islam, Terrorism and Global Business, and U.S. Overseas Investments"
	},
	{
		"name": "Dr. Teri Bingham",
		"title": "Associate Professor of Education",
		"dep": "Education, Department of",
		"building": "Old Main",
		"room": "434",
		"phone": "806-651-2606",
		"email": "tbingham@wtamu.edu",
		"thumb": "/images/teri-bingham-bodyphoto.jpg",
		"url": "/teri-bingham",
		"expertise": "Effective Teaching, Mathematics Education, Peer Coaching, and  Supervision and Conferencing Teachers and Student Teachers"
	},
	{
		"name": "Dr. Tim Steffens",
		"title": "Assistant Professor, Rangeland Resource Management",
		"dep": "Agricultural Sciences",
		"building": "Agriculture and Natural Sciences Building",
		"room": "213 N",
		"phone": "806-651-2781",
		"email": "tsteffens@wtamu.edu",
		"thumb": "/images/tim-steffens-bodyshiot.jpg",
		"url": "/Tim-Steffens",
		"expertise": "Drought Management and Range Hydrology, Grazing Economics, Grazing Management, Habitat Management, Range Livestock Nutrition, Range Wildlife, Rangeland Ecology, and Rangeland Monitoring"
	},
	{
		"name": "Dr. Tina Carpenter",
		"title": "Professor of Music",
		"dep": "Music, School of",
		"building": "Mary Moody Northern Hall",
		"room": "208",
		"phone": "806-651-2848",
		"email": "tcarpenter@wtamu.edu",
		"thumb": "/images/tina-carpenter-bodyphoto.jpg",
		"url": "/tina-carpenter",
		"expertise": "Bassoon Performance and Pedagogy, Music Appreciation, and Music Theory"
	},
	{
		"name": "Dr. Trudy L. Hanson",
		"title": "Professor and Department Chair of Communication Studies",
		"dep": "Communication, Department of",
		"building": "Sybil B. Harringtoni Fine Arts Complex",
		"room": "194",
		"phone": " 806-651-2800",
		"email": "hanson@wtamu.edu",
		"thumb": "/images/trudy-hanson-bodyphoto.jpg",
		"url": "/trudy-hanson",
		"expertise": "Active Learning Techniques, Classroom Assessment and Research, College Teaching, Fractured Fairy Tales&#8212;Texas Style, Gender Communication, Gender Equity in the Classroom, Gender Issues, Oral History, Oral Storytelling to Teach Writing in the Primary Grades, Performance Studies, Popular Culture, Puppetry, Readers Theatre, Reality TV, Rhetorical Criticism, Sexual Harassment in the Workplace, Storytelling, Using Oral Storytelling to Teach Writing Skills, Web-based Learning, and Women in Leadership"
	},
	{
		"name": "Dr. Turkan Dursun Kilic",
		"title": "Assistant Professor of Marketing",
		"dep": "Management, Marketing and General Business, Deptartment of",
		"building": "Classroom Center",
		"room": "213 B",
		"phone": "806-651-2506",
		"email": "tkilic@wtamu.edu",
		"thumb": "/images/turkan-kilic-bodyphoto.jpg",
		"url": "/turkan-kilic",
		"expertise": "Consumer Behavior, International Business, Market Orientation, Marketing, Marketing Research, New Product Development/Management, and Quantitative Analysis"
	},
	{
		"name": "Dr. Ty E. Lawrence",
		"title": "Associate Professor of Animal Science",
		"dep": "Agricultural Sciences",
		"building": "Agriculture and Natural Sciences Building",
		"room": "114 H",
		"phone": "806-651-2560",
		"email": "tlawrence@wtamu.edu",
		"thumb": "/images/ty-lawrence-bodyshot.jpg",
		"url": "/ty-lawrence",
		"expertise": "Conversion of Muscle to Meat, Fresh and Processed Meat Production, Growth and Development of Domestic Farm Animals, and Statistics"
	},
	{
		"name": "Dr. Vanessa Fiaud",
		"title": "Assistant Professor of Sports and Exercise Scinces",
		"dep": "Sports and Exercise Sciences, Department of ",
		"building": "Virgil Henson Activities Center",
		"room": "230",
		"phone": "806-651-2677",
		"email": "vfiaud@wtamu.edu",
		"thumb": "/images/vanessa-fiaud-bodyphoto.jpg",
		"url": "/vanessa-fiaud",
		"expertise": "Balance Issues, Biomechanics, Clinical Biomechanics, and Specific Sports Skills Analysis"
	},
	{
		"name": "Mrs. Vicki Hartin",
		"title": "Instructor of Nursing",
		"dep": "Nursing, Department of ",
		"building": "Old Main",
		"room": "309 C",
		"phone": "806-651-2629",
		"email": "vhartin@wtamu.edu",
		"thumb": "/images/vicki-hartin-bodyphoto.jpg",
		"url": "/vicki-hartin",
		"expertise": "Complimentary Alternative Therapies and Perioperative Nursing"
	},
	{
		"name": "Dr. W. David Sissom",
		"title": "Professor of Biology, Department Head",
		"dep": "Life, Earth and Environmental Sciences, Department of ",
		"building": "Agriculture and Natural Sciences Building",
		"room": "348 A",
		"phone": " 806-651-2573",
		"email": "dsissom@wtamu.edu",
		"thumb": "/images/w-david-sissom-bodyshot.jpg",
		"url": "/w.-david-sissom",
		"expertise": "Entomology, Arachnology (specifically Systematics and Ecology of Scorpions, Systematics of Robber Flies, Systematics of Spiders)"
	},
	{
		"name": "Dr. Wade Shaffer",
		"title": "Academic Provost/Vice President for Academic Affairs and Professor of History",
		"dep": "Academic Affairs",
		"building": "Old Main",
		"room": "407",
		"phone": "806-651-2044",
		"email": "wshaffer@wtamu.edu",
		"thumb": "/images/wade-shaffer-bodyphoto.jpg",
		"url": "/wade-shaffer",
		"expertise": "19th Century American Politics and Journalism, American Colonial, Early American History, History of the American South, Revolutionary and Antebellum History, American Slavery and the Old South, Virginia History. School-University Partnerships, and School-University Partnerships"
	},
	{
		"name": "Mr. William Ambrose",
		"title": "Assistant Professor of Mathematics",
		"dep": "Engineering and Computer Science, and Mathematics, School of ",
		"building": "Classroom Center",
		"room": "417 F",
		"phone": "806-651-2533",
		"email": "bambrose@wtamu.edu",
		"thumb": "/images/william-ambrose-bodyphoto.jpg",
		"url": "/william-ambrose",
		"expertise": " Differential Equations and Probability"
	},
	{
		"name": "Dr. William Jim Rogers",
		"title": "Professor of Environmental Science",
		"dep": "Life, Earth and Environmental Sciences, Department of ",
		"building": "Agriculture and Natural Sciences Building",
		"room": "321 A",
		"phone": "806-651-2581",
		"email": "wrogers@wtamu.edu",
		"thumb": "/images/william-rogers-bodyphoto.jpg",
		"url": "/william-rogers",
		"expertise": "Environmental Monitoring, Environmental Risk Assessment and Compliance, and Waste Site Remediation"
	},
	{
		"name": "Dr. William J. Takacs",
		"title": "Associate Professor of Music",
		"dep": "Music, School of",
		"building": "Mary Moody Northern Hall",
		"room": "142",
		"phone": "806-651-2835",
		"email": "wtakacs@wtamu.edu",
		"thumb": "/images/william-takacs-bodyphoto.jpg",
		"url": "/william-takacs",
		"expertise": "Trumpet Performance and Pedagogy"
	},
	{
		"name": "Dr. Yvette Castillo",
		"title": "Assistant Professor of Counselor Education",
		"dep": "Education, Department of",
		"building": "Old Main",
		"room": "435",
		"phone": "806-651-8233",
		"email": "ycastillo@wtamu.edu",
		"thumb": "/images/yvette-castillo-bodyphoto.jpg",
		"url": "/yvette-castillo",
		"expertise": "Counselor Education and Supervision,Human Growth and Development, Multicultural and Diversity Issues, Professional and School Counseling, Psycho-Social Assessment, and Trauma and Grief"
	}
]